import { anyApi } from "convex/server";

// NOTE: This file is auto-generated by `npx convex dev`. It is committed as a
// stub so the Next.js app type-checks before the Convex deployment is linked.
// Running `npx convex dev` (with CONVEX_DEPLOYMENT + deploy key) regenerates it
// with fully typed function references.
export const api = anyApi;
export const internal = anyApi;
