// Stub regenerated by `npx convex dev`. Kept minimal so `tsc` stays green
// before the Convex deployment is linked.
export type Doc<N extends string> = any;
export type Id<N extends string> = string & { __brand?: N };
export type DataModel = any;
export type TableNames = string;
